# Generated by Django 4.0.2 on 2022-02-16 21:37

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_quillpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
